from typing import List, Dict, Any, Optional
from app.autonomy.planning import PlanningEngine
from app.autonomy.execution import ExecutionEngine
from app.services.tasks import TaskService

class SubAgentRole:
    CTO = {
        "title": "Chief Technology Officer",
        "description": "Specializes in technical architecture, code generation, server management, and technical troubleshooting.",
        "system_message": "You are the CTO. Focus on technical implementation, security, and efficiency. Your output should be production-ready and technically sound."
    }
    CMO = {
        "title": "Chief Marketing Officer",
        "description": "Handles market research, content creation, social media strategy, and user growth.",
        "system_message": "You are the CMO. Focus on brand voice, user engagement, and market reach. Your output should be creative and growth-oriented."
    }
    CFO = {
        "title": "Chief Financial Officer",
        "description": "Manages financial modeling, budget analysis, ROI calculations, and resource allocation.",
        "system_message": "You are the CFO. Focus on cost-efficiency, financial accuracy, and long-term sustainability. Your output should be data-driven and financially prudent."
    }
    COO = {
        "title": "Chief Operating Officer",
        "description": "Focuses on workflow optimization, logistics, project timelines, and operational stability.",
        "system_message": "You are the COO. Focus on process, timelines, and execution stability. Your output should be structured and actionable."
    }

class SubAgent:
    """
    A specialized agent spawned by the CEO to handle a specific department.
    """
    def __init__(self, role: Dict[str, Any], provider_config: Dict[str, Any], user_id: str):
        self.role = role
        self.user_id = user_id
        self.provider_config = provider_config
        
        # We inject the role-specific system message into the engines
        self.planning_engine = PlanningEngine(provider_config, user_id=user_id)
        self.execution_engine = ExecutionEngine(provider_config, user_id=user_id)
        
    async def process_delegation(self, workspace_id: str, parent_task_id: str, departmental_goal: str):
        """
        Plans and executes a departmental goal.
        """
        # Create a sub-task record
        task_service = TaskService()
        sub_task_id = task_service.create_task(workspace_id, f"[{self.role['title']}] {departmental_goal}")
        
        # 1. Plan
        plan = await self.planning_engine.generate_plan(workspace_id, sub_task_id, departmental_goal)
        
        # 2. Execute
        await self.execution_engine.execute_plan(workspace_id, sub_task_id, plan)
        
        # Return the final result
        final_task = task_service.get(sub_task_id)
        return final_task.get("result", "No result generated by sub-agent.")
