"use client";

import { motion } from "framer-motion";
import { Scale, ShieldAlert, UserCheck, FileText, ArrowLeft, Lock } from "lucide-react";
import Link from "next/link";

export default function TermsPage() {
    const points = [
        {
            title: "Data Sovereignty",
            desc: "You retain 100% ownership of your workspace data, evolved modules, and agent logic. Quantify OS does not claim intellectual property over your autonomous creations.",
            icon: <UserCheck className="text-emerald-500" size={24} />
        },
        {
            title: "Agent Accountability",
            desc: "You are the ultimate sovereign of your AI swarm. While the OS provides safety simulators (Shadow Traces), you remain responsible for the actions taken by agents within your workspace.",
            icon: <ShieldAlert className="text-amber-500" size={24} />
        },
        {
            title: "Kill-Switch Rights",
            desc: "You have the undisputed right to halt any and all processes. We provide platform-level safeguards, but you are the final authority on system termination.",
            icon: <Lock className="text-indigo-500" size={24} />
        }
    ];

    return (
        <div className="min-h-screen bg-[#020202] text-zinc-300 font-sans p-6 md:p-12">
            <div className="fixed inset-0 bg-[radial-gradient(circle_at_0%_100%,#4f46e508,transparent_50%)] pointer-events-none" />

            <header className="max-w-4xl mx-auto mb-20 relative z-10 text-center">
                <Link href="/" className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-widest text-zinc-500 hover:text-white transition-colors mb-8">
                    <ArrowLeft size={14} /> Back to Interface
                </Link>
                <div className="flex flex-col items-center gap-6">
                    <div className="p-4 bg-white/5 rounded-3xl border border-white/10 text-white">
                        <Scale size={40} />
                    </div>
                    <h1 className="text-6xl font-black text-white tracking-tighter uppercase tracking-[0.1em]">Terms of <span className="text-indigo-500">Sovereignty.</span></h1>
                    <p className="text-zinc-500 text-lg max-w-xl font-medium">
                        Clear, authoritative protocols for operating in an autonomous world.
                    </p>
                </div>
            </header>

            <main className="max-w-4xl mx-auto space-y-20 relative z-10">
                <section className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    {points.map((point, i) => (
                        <div key={i} className="p-8 rounded-3xl bg-[#080808] border border-white/5 space-y-4">
                            {point.icon}
                            <h3 className="text-xs font-black text-white uppercase tracking-widest">{point.title}</h3>
                            <p className="text-[11px] leading-relaxed text-zinc-500 font-medium">{point.desc}</p>
                        </div>
                    ))}
                </section>

                <section className="space-y-12">
                    <div className="flex items-center gap-3">
                        <FileText className="text-indigo-500" size={20} />
                        <h2 className="text-xl font-black text-white uppercase tracking-widest">Protocol Clauses</h2>
                    </div>

                    <div className="space-y-10">
                        <div className="space-y-3">
                            <h4 className="text-[10px] font-black text-white uppercase tracking-widest">Article 1: Intelligence Transmission</h4>
                            <p className="text-sm text-zinc-500 leading-relaxed font-medium">
                                Communication between your workspace and external providers (e.g., OpenAI, Anthropic) is mediated through our Deterministic Kernel. Metadata is stripped to ensure cryptographic privacy before leaving our infrastructure.
                            </p>
                        </div>
                        <div className="space-y-3 border-l-2 border-indigo-500/20 pl-6">
                            <h4 className="text-[10px] font-black text-white uppercase tracking-widest">Article 2: Evolutionary Licensing</h4>
                            <p className="text-sm text-zinc-500 leading-relaxed font-medium">
                                Modules generated by the Perpetual Evolution Loop are licensed exclusively to you under a Sovereign Open-Source license. You may export, modify, or delete these modules at any time without platform dependency.
                            </p>
                        </div>
                        <div className="space-y-3">
                            <h4 className="text-[10px] font-black text-white uppercase tracking-widest">Article 3: Platform Liability</h4>
                            <p className="text-sm text-zinc-500 leading-relaxed font-medium">
                                Quantify OS provides the infrastructure for autonomy. We are not liable for economic losses resulting from autonomous budget allocation or agent-led micro-transactions. Use the Sovereign Wallet with appropriate risk governance.
                            </p>
                        </div>
                    </div>
                </section>
            </main>

            <footer className="max-w-4xl mx-auto mt-32 py-10 border-t border-white/5 text-center">
                <p className="text-[9px] font-black text-zinc-700 uppercase tracking-[0.4em]">TERMS_LAST_UPDATED: 2026.03.04 // KERNEL_v15_SOVEREIGN</p>
            </footer>
        </div>
    );
}
